### ISSUE TITLE
Not exporting as OBJ

### ISSUE THREAD

**Issue by mrmario7502** [RenolY2/bw-model-viewer#2]
Hi there!  Trying to get the model files into a usable format for Blender.  Right now, when I choose the Export Current as OBJ option, I don't get an OBJ file.  Everything is completely dismantled, and the 3D model is a BGF.

I'm sure I'm missing something simple!  Any help would be appreciated

**Comment by RenolY2** [comment]
If you are seeing it as BGF then that probably means your files explorer is hiding file extensions because the file extension is .bgf.obj. The .bgf is coming from the model's internal name but otherwise doesn't mean much, the exported file is an .obj and Blender is able to import the file which I tested just now. Some of the exported models may have pieces that aren't in the correct place, that's a flaw in the exporter but I do not know how to fix that so I recommend fixing the model yourself by looking at where the model pieces should be ingame.

**Comment by mrmario7502** [comment]
Thank you!  You're totally right, my File Explorer wasn't labeling them right.  Monkeyed around with it and got them into Blender no problem.
